name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: saitejakm
          template: classic
          config_timezone: Asia/Kolkata

          # Core sections
          base: header, activity

          # Count contributions from your work repos also
          repositories_affiliations: owner, collaborator, organization_member

          # Output svg
          filename: github-metrics.svg

          # Show Pull Requests (created, merged, reviewed)
          plugin_pullrequests: yes
          plugin_pullrequests_sections: created, merged, reviewed

          # Show PR, commit & issue contributions summary
          plugin_contributors: yes
          plugin_contributors_sections: commits, pull_requests
          plugin_contributors_limit: 5

      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "Update metrics" || echo "No changes"
          git push
